# Generated by Django 4.2.23 on 2025-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('finished', 'Finished Product'), ('other', 'Other')], default='raw', max_length=20),
        ),
    ]
