# Generated by Django 4.2.23 on 2025-06-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ogarequest_customer_name'),
    ]

    operations = [
    ]
