# Generated by Django 4.2.23 on 2025-06-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20250624_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('mehandi', 'Mehandi'), ('resin', 'Resin')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('add', 'Add'), ('sell', 'Sell')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_oga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ogarequest')),
            ],
        ),
    ]
