# Generated by Django 4.2.23 on 2025-07-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
