# Generated by Django 4.2.23 on 2025-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_deliveryticket_tracking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogarequest',
            old_name='name',
            new_name='oga_name',
        ),
        migrations.AddField(
            model_name='ogarequest',
            name='full_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ogarequest',
            name='landmark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ogarequest',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='oga_screenshots/'),
        ),
        migrations.AddField(
            model_name='ogarequest',
            name='stock_type',
            field=models.CharField(choices=[('mehandi', 'Mehandi'), ('resin', 'Resin')], default='resin', max_length=20),
        ),
    ]
