# Generated by Django 4.2.23 on 2025-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_name_ogarequest_oga_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogarequest',
            name='screenshot',
            field=models.ImageField(upload_to='oga_screenshots/'),
        ),
    ]
