# Generated by Django 4.2.23 on 2025-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_ogarequest_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(choices=[('mehandi', 'Mehandi'), ('resin', 'Resin')], max_length=20),
        ),
    ]
