# Generated by Django 4.2.23 on 2025-06-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_stock_name_remove_stock_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogarequest',
            name='stock_type',
            field=models.CharField(choices=[('resin', 'Resin'), ('mehandi', 'Mehandi')], default='resin', max_length=20),
        ),
    ]
